const db = [
  {
    "n": "Essodokam ABABOHOU",
    "e": "abadoesso@gmail.com",
    "p": "EOPP",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mahamadou Hafizou ADAMOU DJIBO",
    "e": "hafizouadamou1@gmail.com",
    "p": "AIAA",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Adewale Alexandre ADEROMOU",
    "e": "aderowa2000@gmail.com",
    "p": "KIQN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Fifam Gbenoukpo Chrisl ADJADJIHOUE",
    "e": "chrislaadj@gmail.com",
    "p": "MTJS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Yawovi honor ADJAH",
    "e": "honoresena16@gmail.com",
    "p": "SIOM",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Hounangnon Georges AGUEHOUNDE",
    "e": "aguehoundegeorges@gmail.com",
    "p": "HRPR",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mindessi Dieudonn AKPOVI",
    "e": "akpovidm@gmail.com",
    "p": "WHIS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Arnaud ALLOSSOGBE",
    "e": "arnaulloss@gmail.com",
    "p": "MLKQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Biova Elom AMELEWONOU",
    "e": "elomdeborah19@yahoo.fr",
    "p": "HKBJ",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Godwill Todema AMOUSSOU-ZANNOU",
    "e": "amoussougodwill1@gmail.com",
    "p": "PZXG",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Torrs Kessel Sdric Godonou APITHY",
    "e": "torreskessel.apithy@gmail.com",
    "p": "UZDZ",
    "t": 57,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Gbdossou Martin ASSI",
    "e": "aissimartin99@gmail.com",
    "p": "YZTJ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "C. Euphrem ATREKOU",
    "e": "atrekoueuphrem@gmail.com",
    "p": "CJEH",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Yaye Diba BA",
    "e": "relatik568@gmail.com",
    "p": "QIBF",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Bakary BALLO",
    "e": "koinbakary@yahoo.fr",
    "p": "YAPK",
    "t": 45,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : CAS PRATIQUE 1",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : CAS PRATIQUE 3",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Saikou Yaya BARRY",
    "e": "saikouyayabarry85@gmail.com",
    "p": "MDJU",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Adama BERTHE",
    "e": "adamaberthe84@gmail.com",
    "p": "PPMM",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Dgbdji Achille Isral BINO",
    "e": "israelbinoi026@gmail.com",
    "p": "HFRA",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Daouda BONKOUNGOU",
    "e": "bonkoungoudaouda5@gmail.com",
    "p": "PWGQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "koffi KOUASSI CHARLES",
    "e": "charlesk_kouassi@yahoo.fr",
    "p": "RLRU",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Cyrile Gabain CHIMI MEPOUONG",
    "e": "chimicyrille@gmail.com",
    "p": "OFWM",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoulaye CISSE",
    "e": "cisseabdoulaye118@gmail.com",
    "p": "MPQF",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Aboubacar CISSE",
    "e": "aboubacarcisse72@gmail.com",
    "p": "UBGI",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Thierry COMLAN",
    "e": "comlanthierry@yahoo.fr",
    "p": "FGNH",
    "t": 48,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : Forum 2",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Batjini COULIBALY",
    "e": "batjini1@gmail.com",
    "p": "BDYW",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Yemporb DANKOULE",
    "e": "ydankoule@gmail.com",
    "p": "LPNQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mariatou DIA",
    "e": "marietoud510@gmail.com",
    "p": "DDJQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ousmane DIABATE",
    "e": "diabnai@yahoo.fr",
    "p": "GYCM",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Diame DIAHAME",
    "e": "ddiahame@hotmail.com",
    "p": "WWMS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Amadou DIALLO",
    "e": "amadoudiallo207@gmail.com",
    "p": "ZFVV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mahmoudou DIALLO",
    "e": "mahodia2k@yahoo.fr",
    "p": "XDKF",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Jaques Lazare Ska DIATTA",
    "e": "lazareseka09@gmail.com",
    "p": "EESZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoul Aziz DIOP",
    "e": "abdouldiop@hotmail.com",
    "p": "SUZB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Salifou DJIBO BAGNA",
    "e": "salifou.djibo@fiducs-niger.com",
    "p": "BSGV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Yemboado DJOLGOU",
    "e": "pascydjol@gmail.com",
    "p": "AZKZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Seydou DOUMBIA",
    "e": "namatakom03@gmail.com",
    "p": "EQGH",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Morissanda DOUMBIA",
    "e": "morissandadoumbia64@gmail.com",
    "p": "EXAF",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Koku Agbenyo EDZAGBO",
    "e": "kedzagbo@yahoo.fr",
    "p": "WOXB",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Michel Waly FAYE",
    "e": "michelw.faye@gmail.com",
    "p": "LXCN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoul salam GANAMA",
    "e": "abganama@yahoo.fr",
    "p": "SGON",
    "t": 54,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : CAS PRATIQUE 1",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Charafath Adeboumi Agnike GANGBO",
    "e": "gangbofolachade@gmail.com",
    "p": "FSNU",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Terbi Clovis GARANGO",
    "e": "clovis_garango@outlook.com",
    "p": "BCXI",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoul Aziz GARBA MAMOUDOU",
    "e": "garbaabdoulaziz569@gmail.com",
    "p": "LEKS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdourahmane GAYE",
    "e": "gayeabou993@gmail.com",
    "p": "SWAY",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Protus Julius Ezechiel GBOSSAME",
    "e": "gprotus@hotmail.com",
    "p": "JOQZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Armel Flix GNAHOUI",
    "e": "armelix03@gmail.com",
    "p": "SKSG",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Serge Brice GNAHOUI",
    "e": "sergebgn@outlook.fr",
    "p": "YVJN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Roseline Marina GUENDEHOU",
    "e": "rosmarie84@yahoo.fr",
    "p": "FLDJ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Oundieu Serge GUEU",
    "e": "oundieus@gmail.com",
    "p": "IRIO",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "James Smith HOUEGBELOSSI",
    "e": "jshouegbelossi@gmail.com",
    "p": "ZXOC",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Katch Parfait HOUEHOU",
    "e": "hkatche@yahoo.fr",
    "p": "CKJB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mouftaou  V.  Dsir HOUNKPONOU",
    "e": "prestigedes@yahoo.fr",
    "p": "XOZB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Almouctar Ibrahim IDDER",
    "e": "almouctaridder@gmail.com",
    "p": "KHLX",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Aboubakar Sekou IKIDE",
    "e": "ikideaboubakarsekou@gmail.com",
    "p": "QMFB",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Moctar ISSA HARY",
    "e": "moctarsinder@gmail.com",
    "p": "TGSB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Enagnon Yves JIMAJA",
    "e": "aupickj@yahoo.fr",
    "p": "CDRM",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Balmwend Eliane Adonija KABORE",
    "e": "eliane.kabore@forvismazars.com",
    "p": "KPBE",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Nongassida KAFANDO",
    "e": "nongassidak@gmail.com",
    "p": "VFJZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Saimby Bindes Loc KEME",
    "e": "saimbykeme@gmail.com",
    "p": "OJKD",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Bandiougou KETA",
    "e": "b.keita.9404@gmail.com",
    "p": "SGOX",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Drissa KETA",
    "e": "drissakeita69@gmail.com",
    "p": "RSLZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Amitou Christ Titania KINI",
    "e": "kiniamitou@gmail.com",
    "p": "YQPZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Gildas Mahoutin KODONON",
    "e": "gildaskodonon3@gmail.com",
    "p": "WJVC",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoul Aziz KONATE",
    "e": "abdoulazizkonate7@gmail.com",
    "p": "CBKC",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Komi KONDO",
    "e": "kondokomi2@gmail.com",
    "p": "YSKQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Boris KOUAKOU",
    "e": "boris.simon.kouakou@gmail.com",
    "p": "BPQF",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Kossi KOUDADJE",
    "e": "jpkossi@gmail.com",
    "p": "JNCB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "G.Ditorga KOUMASSI",
    "e": "ditorga@yahoo.fr",
    "p": "HFKI",
    "t": 57,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Gabriel KPATOUKPA",
    "e": "kpatoukpa_gabriel@yahoo.fr",
    "p": "TSZU",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Michal Constant KPONGBO",
    "e": "nogedi2006@yahoo.fr",
    "p": "ZUXB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Gerardo Ambroise Sena MAROYA",
    "e": "margeams@gmail.com",
    "p": "AMXS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Godonou Judical MITOLODE",
    "e": "mitolodejudical@yahoo.fr",
    "p": "SKZD",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "N'Goran Nestor N'BANDAMAN",
    "e": "n.nbandaman@yahoo.com",
    "p": "OEUK",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Kouamé Célestin N'GUESSAN",
    "e": "cknguess2003@yahoo.fr",
    "p": "UCFN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Kodjo N'TARE",
    "e": "gildasntare@gmail.com",
    "p": "GPTA",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Yasmina Amira NARE",
    "e": "yasminanare6@gmail.com",
    "p": "KWAW",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Fama NDAO",
    "e": "famandao300@gmail.com",
    "p": "UOUS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mouhamed NDIAYE",
    "e": "ndiayemohamed7@hotmail.com",
    "p": "POEG",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Marieme NDIAYE",
    "e": "marieme.ndiaye@forvismazars.com",
    "p": "RHUL",
    "t": 0,
    "m": []
  },
  {
    "n": "KOUAME DIEU-DONNE CHARLES NGORAN",
    "e": "ngoran.kouame26@gmail.com",
    "p": "KDMQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Seydina Issa Laye NIANG",
    "e": "seydinaissalayeniang6@gmail.com",
    "p": "PRCV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ndeye Mbadam NIANG",
    "e": "nmniang@yahoo.com",
    "p": "NRTW",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Thierry Arnaud OUEDRAOGO",
    "e": "othierryarnaud@gmail.com",
    "p": "DLZV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "S. Edouard OUEDRAOGO",
    "e": "edouard6402@gmail.com",
    "p": "UCTZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ruth Michaëline OUEDRAOGO",
    "e": "ruthmichaeline@yahoo.com",
    "p": "KJCF",
    "t": 57,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Moussa OUMAROU ABDOU",
    "e": "moussa.mao@mac.ne",
    "p": "JTIO",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ismael PORGO RASMANE",
    "e": "pismael34@gmail.com",
    "p": "NYRV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abzta RAMDE",
    "e": "abzeta_ramde@yahoo.fr",
    "p": "ZZUW",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Adama ROUAMBA",
    "e": "adamarouamba5@gmail.com",
    "p": "KKYQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Akim SABI ZINGUI",
    "e": "sazkim21@gmail.com",
    "p": "EAES",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Nabirou SACARI",
    "e": "nabirousacari@gmail.com",
    "p": "OHNH",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Raoul SAGNA",
    "e": "gnasara78@gmail.com",
    "p": "EISN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ismael SALISSOU SITTOU",
    "e": "salissousittou777@gmail.com",
    "p": "BSOZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Harouna SAMAKE",
    "e": "masaharouna@yahoo.fr",
    "p": "PWFK",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Cheikh Tidiane SAMB",
    "e": "samb.cheikhtidiane@gmail.com",
    "p": "BELD",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Lacina SANGARE",
    "e": "lacinasangare@yahoo.fr",
    "p": "GYMI",
    "t": 57,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Brahima SANKARA",
    "e": "sankisbrah@gmail.com",
    "p": "AAGK",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Massogholo Latifah SANOGO",
    "e": "sanogolatifah08@gmail.com",
    "p": "BPJS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Banawa Lotta Eric SANTA",
    "e": "eric.santa.es@gmail.com",
    "p": "SBYQ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Abdoulaye SARR",
    "e": "sarrabdoulaye22@gmail.com",
    "p": "TIBJ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Wendkouni Rodrigue SAWADOGO",
    "e": "rosawadogo2015@gmail.com",
    "p": "NUGH",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mame Ndack SECK",
    "e": "seckmamendack@gmail.com",
    "p": "KIQR",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "G. I. Laurence SEDODE",
    "e": "ida.laurence@yahoo.fr",
    "p": "TALA",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Foquet Franck SEFON",
    "e": "sefon_foquet@yahoo.fr",
    "p": "LNFX",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Ibrahima Khalil SENE",
    "e": "ibkhsene@gmail.com",
    "p": "HVVO",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Koku Degbe SEWA",
    "e": "richardbonheur84@gmail.com",
    "p": "NUGV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Tassr SIMPORE",
    "e": "simporetassere8@gmail.com",
    "p": "XHJO",
    "t": 60,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Modibo SISSOKO",
    "e": "modibo10343@gmail.com",
    "p": "SOAO",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Moussa SISSOKO",
    "e": "tiemadebally@gmail.com",
    "p": "YCSR",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Sientchanhoua Johan SORO",
    "e": "johansoro65@gmail.com",
    "p": "HIVN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Sayouba SORO",
    "e": "sorosayoub93@gmail.com",
    "p": "CKTN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Fama SY",
    "e": "famasy548@gmail.com",
    "p": "BSWJ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Assimahou Monrènikè TASSOU",
    "e": "asmatassou08@gmail.com",
    "p": "SWFH",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Rodolpho Alid Solvo Emmanuel TOGBE",
    "e": "rodolphotogbe@gmail.com",
    "p": "MSRG",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Joshua Jean-Jacques Ekou TOMETY",
    "e": "joshuatomety@yahoo.fr",
    "p": "XRIO",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mabel Geoffroy Elise TOUPE",
    "e": "mtoupe13@gmail.com",
    "p": "UCZB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mouhammad Al- Amine TOURE",
    "e": "alamine.toure@cec-alo.ci",
    "p": "XZAN",
    "t": 2,
    "m": [
      "MODULE 3 : CAS PRATIQUE 3"
    ]
  },
  {
    "n": "Mamadou TOURE-DERUOTH",
    "e": "fininvest40@gmail.com",
    "p": "AFBB",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Herv VIGAN",
    "e": "vigane.he@gmail.com",
    "p": "SKRN",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Maman Mansour YAHAYA BACHARD",
    "e": "mansbach81@gmail.com",
    "p": "ZBZB",
    "t": 2,
    "m": [
      "MODULE 3 : CAS PRATIQUE 3"
    ]
  },
  {
    "n": "Abdoul Nasser YAHIA ABDOULAYE",
    "e": "nabdoul54@yahoo.fr",
    "p": "KPYW",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Tonakpon Saint Avant YANHA",
    "e": "yanhaavant8@gmail.com",
    "p": "RTLE",
    "t": 51,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : CAS PRATIQUE 1",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Zakaria YARO",
    "e": "yarozakaria6@gmail.com",
    "p": "TSWZ",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Lorng Miche David YEDESS",
    "e": "lorngyedess@gmail.com",
    "p": "XZJD",
    "t": 2,
    "m": [
      "MODULE 3 : CAS PRATIQUE 3"
    ]
  },
  {
    "n": "kodjovi Djifa YENOUDJI",
    "e": "nyedjifa@gmail.com",
    "p": "UOXV",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Cyrille Armand YOMBO A KOUL",
    "e": "cyrilleyombo@yahoo.fr",
    "p": "DGPY",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Mouyibenkou Sidoine YONOUWINHI",
    "e": "ym.sidoine@gmail.com",
    "p": "TFFT",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  },
  {
    "n": "Said Ayind YOROBA",
    "e": "saidayindeyoroba@gmail.com",
    "p": "RQWS",
    "t": 62,
    "m": [
      "EVALUATION DES JT DECOFI",
      "Module 1 : Forum 1",
      "Module 1 : CAS PRATIQUE 1",
      "Module 1 : Forum 2",
      "Module 1 : Forum 3",
      "Module 2: QCM 1",
      "Module 2 : FORUM  2",
      "Module 2 : CAS PRATIQUE 3",
      "MODULE 3 : FORUM 1",
      "MODULE 3 : CAS PRATIQUE 2",
      "MODULE 3 : FORUM 3",
      "MODULE 3 : CAS PRATIQUE 3",
      "MODULE 4 : CAS PRATIQUE 1",
      "MODULE 4 : Forum 1",
      "MODULE 4 : CAS PRATIQUE 2",
      "MODULE 4 : CAS PRATIQUE 3",
      "MODULE 5 : CAS PRATIQUE 1",
      "MODULE 5 : FORUM 1",
      "MODULE 5 : FORUM 2",
      "MODULE 5 : CAS PRATIQUE 3",
      "MODULE 5 : FORUM 4",
      "EVALUATION DES JT 1.3"
    ]
  }
];
